### ISSUE TITLE
don't exit simulation.

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#10]
```
10062 INFO Watson(localhost:55555) は、client.#.dbの回収に乗り出した。
10062 INFO Watson(localhost:55555) なんて言いながら実は待機してるだけ。
10063 INFO Watson(localhost:55555) client.1.dbの回収完了。
10063 INFO Watson(localhost:55555) client.#.db の結合開始。
10063 INFO Watson(localhost:55555) client.#.db の結合終了。
```
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./simulation.py", line 13, in make_client
    client.start()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 130, in start
    recved_msg = self._tcp_sock.recv(1024)
```

**Comment by umedoblock** [comment]
```
10045 INFO watson._release_clients()
10046 INFO type(tcp_office_client)=<class 'socket.socket'> in _release_clients()
10046 INFO tcp_office_client=<socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0> in _release_clients()
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/watson.py", line 242, in run
    self._release_clients()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/watson.py", line 367, in _release_clients
    self._tcp_sock.send(result, tcp_office_client)
AttributeError: 'Watson' object has no attribute '_tcp_sock'
```
