### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#16]
Traceback (most recent call last):
  File "tools/make_simulation_db.py", line 130, in <module>
    args, simulation_db_path = args_make_simulation_db()
  File "tools/../lib/args.py", line 54, in args_make_simulation_db
    simulation_db_path = _get_simulation_db_path(args)
  File "tools/../lib/args.py", line 32, in _get_simulation_db_path
    simulation_db_path = _normalize_db_or_log_path(args)
  File "tools/../lib/args.py", line 150, in _normalize_db_or_log_path
    files = os.listdir(dir_name)
NotADirectoryError: [Errno 20] Not a directory: './umatobi-simulation/simulator.sql.log'

**Comment by umedoblock** [comment]
refs #11
