### ISSUE TITLE
sqlite3.OperationalError: table xxx already exists

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#160]
permit to occur
sqlite3.OperationalError: table xxx already exists
#159

**Comment by umedoblock** [comment]
```
FAILED (errors=1)
Traceback (most recent call last):
  File "./tests/unit_test.py", line 42, in <module>
    test_main()
  File "./tests/unit_test.py", line 34, in test_main
    run_unittest(unit_suite)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/support/__init__.py", line 1995, in run_unittest
    _run_suite(suite)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/support/__init__.py", line 1914, in _run_suite
    raise TestFailed(err)
test.support.TestFailed: Traceback (most recent call last):
  File "/Users/umedoblock/github.com/umatobi/umatobi/tests/unit/test_darkness.py", line 201, in test_darkness__leave_here
    client_db.create_table('growings')
  File "/Users/umedoblock/github.com/umatobi/umatobi/simulator/sql.py", line 82, in create_table
    self.execute(sql)
  File "/Users/umedoblock/github.com/umatobi/umatobi/simulator/sql.py", line 152, in execute
    rows = self._cur.execute(sql)
sqlite3.OperationalError: table growings already exists
```
