### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#20]
#18
```
7691 watson DEBUG watson time.sleep(1.0)pid=12694, thread_id=140346509780800
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 46, in run
    Polling.run(self)
  File "/home/umedoblock/git.me/umatobi/umatobi/lib/__init__.py", line 33, in run
    self._sche.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/home/umedoblock/git.me/umatobi/umatobi/lib/__init__.py", line 29, in _polling
    self.polling()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 60, in polling
    self.inhole_queues_from_nodes()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 75, in inhole_queues_from_nodes
    self.client_db.insert('growings', growing)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/sql.py", line 169, in insert
    self.execute(sql, values)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/sql.py", line 143, in execute
    rows = self._cur.execute(sql, values)
sqlite3.OperationalError: database is locked
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 46, in run
    Polling.run(self)
  File "/home/umedoblock/git.me/umatobi/umatobi/lib/__init__.py", line 33, in run
    self._sche.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "/home/umedoblock/git.me/umatobi/umatobi/lib/__init__.py", line 29, in _polling
    self.polling()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 60, in polling
    self.inhole_queues_from_nodes()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 75, in inhole_queues_from_nodes
    self.client_db.insert('growings', growing)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/sql.py", line 169, in insert
    self.execute(sql, values)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/sql.py", line 143, in execute
    rows = self._cur.execute(sql, values)
sqlite3.OperationalError: database is locked
```

**Comment by umedoblock** [comment]
これももう，再現しないと思う。
