### ISSUE TITLE
FileExistsError: [Errno 17] File exists: 

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#216]
```
test__confesses_darkness (test_client.ClientTests) ... Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/umedoblock/github.com/umatobi/umatobi/simulator/client.py", line 18, in make_darkness
    darkness_ = Darkness(**d_config)
  File "/Users/umedoblock/github.com/umatobi/umatobi/simulator/darkness.py", line 121, in __init__
    set_simulation_schema(self.start_up_orig)
  File "/Users/umedoblock/github.com/umatobi/umatobi/lib/__init__.py", line 284, in set_simulation_schema
    make_simulation_dir(simulation_dir_path)
  File "/Users/umedoblock/github.com/umatobi/umatobi/lib/__init__.py", line 296, in make_simulation_dir
    os.makedirs(simulation_dir_path)
  File "/Users/umedoblock/github.com/umatobi/.local/bin/../lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/umedoblock/github.com/umatobi/umatobi/tests/umatobi-simulation/2019-12-05T210813'
```

**Comment by umedoblock** [comment]
```
======================================================================
FAIL: test_get_simulation_dir_path (test_lib.LibTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/umedoblock/github.com/umatobi/umatobi/tests/unit/test_lib.py", line 578, in test_get_simulation_dir_path
    self.assertTrue(os.path.isdir(simulation_dir_path))
AssertionError: False is not true

======================================================================
FAIL: test_set_simulation_schema (test_lib.LibTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/umedoblock/github.com/umatobi/umatobi/tests/unit/test_lib.py", line 606, in test_set_simulation_schema
    f"INFO:umatobi:shutil.copyfile(SIMULATION_SCHEMA_PATH={SIMULATION_SCHEMA_PATH}, simulation_schema_path={simulation_schema_path})")
AssertionError: "INFO:umatobi:os.makedirs('/Users/umedobl[71 chars]23')" != 'INFO:umatobi:shutil.copyfile(SIMULATION_[211 chars]ema)'
- INFO:umatobi:os.makedirs('/Users/umedoblock/github.com/umatobi/umatobi/tests/umatobi-simulation/2019-12-05T211123')
+ INFO:umatobi:shutil.copyfile(SIMULATION_SCHEMA_PATH=/Users/umedoblock/github.com/umatobi/umatobi/simulator/simulation.schema, simulation_schema_path=/Users/umedoblock/github.com/umatobi/umatobi/tests/umatobi-simulation/2019-12-05T211123/simulation.schema)


----------------------------------------------------------------------

Ran 312 tests in 133.815s

FAILED (failures=2)
Traceback (most recent call last):
  File "tests/unit_test.py", line 22, in <module>
    test_main()
  File "tests/unit_test.py", line 19, in test_main
    run_unittest(unit_suite)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/support/__init__.py", line 1995, in run_unittest
    _run_suite(suite)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/support/__init__.py", line 1914, in _run_suite
    raise TestFailed(err)
test.support.TestFailed: multiple errors occurred
```
