### ISSUE TITLE
umatobi-simulation dir 以下に admin.log, simulator.sql.log が存在する。

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#39]
これは bug 認定して良いでしょう。

**Comment by umedoblock** [comment]
いや，これはしょうがない？
timestamp を決定できない状態での log だから？
う〜ん。
決定した後に移動させればよいだけ？

よく分からないや。
対応するかしないかを後で検討しよう。

**Comment by umedoblock** [comment]
うーんにゃ。
bug かな。と、新調したPCから書き込みしながら思っている。
だって，，，へんな例外吐いて死んじゃうんだもん。
```
C:\Users\ASUS\github.com\umatobi\umatobi>python simulation.py --num-nodes=30
Traceback (most recent call last):
  File "simulation.py", line 9, in <module>
    from simulator.client import Client
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\client.py", line 8, in <module>
    from simulator.darkness import Darkness
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\darkness.py", line 7, in <module>
    import simulator.sql
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\sql.py", line 19, in <module>
    level=logger_args.log_level)
  File "C:\Users\ASUS\github.com\umatobi\umatobi\lib\__init__.py", line 141, in make_logger
    fh = logging.FileHandler(log_path)
  File "C:\Python\Python37\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python\Python37\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ASUS\\github.com\\umatobi\\umatobi\\umatobi-simulation\\simulator.sql.log'
```

**Comment by umedoblock** [comment]
bug 認定員会です。
これは，bug  です。

> いや，これはしょうがない？
> timestamp を決定できない状態での log だから？

何がしょうがないですか。
決定できない状態だったら，
console に出力するだけにしておいてください。

変な例外云々いっているのもbugです。
ただし，別ticketにしました。

**Comment by umedoblock** [comment]
#65 によって，対応の必要はなくなりました。
