### ISSUE TITLE
dir name に，":" を含ませると，windowsで例外を吐く。

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#44]
#39
windows だと特有のbugになって面倒臭いなぁ。
```
C:\Users\ASUS\github.com\umatobi\umatobi>python simulation.py --num-nodes=30
281 admin INFO start_up_time=2018-12-09T00:49:09.300080, pid=12152, thread_id=11080
281 admin INFO simulation start !, pid=12152, thread_id=11080
Traceback (most recent call last):
  File "simulation.py", line 104, in <module>
    os.makedirs(dir_name, exist_ok=True)
  File "C:\Python\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] ファイル名、ディレクトリ名、またはボリューム ラベルの構文が間違っています。: './umatobi-simulation\\2018-12-09T00:49:09.300080'

C:\Users\ASUS\github.com\umatobi\umatobi>mkdir a:b
指定されたドライブが見つかりません。

C:\Users\ASUS\github.com\umatobi\umatobi>mkdir ab

C:\Users\ASUS\github.com\umatobi\umatobi>mkdir "a:b"
指定されたドライブが見つかりません。
```

**Comment by umedoblock** [comment]
これは完全なbug。

**Comment by umedoblock** [comment]
作業方針は，
":" を失くして，
timestampは
"年-月-日T時分秒",
にしよう。

**Comment by umedoblock** [comment]
げげっ。
windows で書いた内容が自動的に更新されてる。。。

**Comment by umedoblock** [comment]
はぁ。
```
:!grep isoformat -r . --color
./simulator/watson.py:                'start_up_time': self.server.start_up_orig.isoformat(),
./simulator/watson.py:        self.start_up_time = self.start_up_orig.isoformat()
./simulator/node.py:from lib import formula, elapsed_time, validate_kwargs, isoformat_time_to_datetime
./simulator/node.py:        self.start_up_orig = isoformat_time_to_datetime(self.start_up_time)
./simulator/client.py:from lib import SCHEMA_PATH, isoformat_time_to_datetime
./simulation.py:    start_up_time = start_up_orig.isoformat()
./simulation.py:  # |-- 20121008T180459 # isoformat(), dirname = simulation_dir + isoformat()
./simulation.py:  # `-- 20121008T200822 # isoformat()
./test/test_sql.py:        test['now'] = lib.current_isoformat_time()
./test/test_sql.py:        d_insert['now'] = lib.current_isoformat_time()
./test/test_sql.py:        d_insert['now'] = lib.current_isoformat_time()
./test/test_sql.py:        d_update['now'] = lib.isoformat_time(t)
./test/test_sql.py:        d_insert['now'] = lib.current_isoformat_time()
./test/test_sql.py:        d_update['now'] = lib.isoformat_time(t)
バイナリファイル ./lib/__pycache__/__init__.cpython-36.pyc に一致しました
./lib/__init__.py:def isoformat_time(t):
./lib/__init__.py:def current_isoformat_time():
./lib/__init__.py:    return isoformat_time(now)
./lib/__init__.py:def isoformat_time_to_datetime(s):

:!grep isoformat -r . -l
./simulator/watson.py
...
./simulator/node.py
./simulator/client.py
./simulation.py
./test/test_sql.py
./lib/__init__.py
./lib/.__init__.py.swp
```

**Comment by umedoblock** [comment]
対応済み。
