### ISSUE TITLE
時々死ぬ。

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#55]
生きろっ！
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/screen.py", line 287, in run
    e = self.inhole_pickles_from_simlation_db(passed_ms)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/screen.py", line 339, in inhole_pickles_from_simlation_db
    self.label_area.update('\n'.join(L))
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/screen.py", line 369, in update
    self._buf.set(message)
AttributeError: 'LabelArea' object has no attribute '_buf'
```

**Comment by umedoblock** [comment]
AttributeError: 'LabelArea' object has no attribute '_buf'

いい加減に直した。
