### ISSUE TITLE
object has no attribute 'simulation_milliseconds'

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#56]
#44 からの派生
```
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\OpenGL\GLUT\special.py", line 130, in safeCall
    return function( *args, **named )
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\screen.py", line 129, in _display
    self.display_main(self, passed_seconds)
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\screen.py", line 148, in display_main_thread
    if get_passed_ms(self.start_the_movie_time) > self.manipulating_db.simulation_milliseconds:
AttributeError: 'ManipulatingDB' object has no attribute 'simulation_milliseconds'
GLUT Display callback <bound method Screen._display of <simulator.screen.Screen object at 0x0000027E756A2F98>> with (),{} failed: returning None 'ManipulatingDB' object has no attribute 'simulation_milliseconds'
```

**Comment by umedoblock** [comment]
https://github.com/umedoblock/umatobi/commit/7c1049627ef5b686a893ea7851495a4ea80afb22#diff-7c1a46ff5035fb731eedf135b3b5a93c
で対応済み
