### ISSUE TITLE
UnicodeDecodeError: 'cp932' codec can't decode byte 0x88 in position 1081: illegal multibyte sequence

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#57]
これも，#44からの派生。
これは，どう解決するんがいいだろうか。
cmd.exe で
`chcp 65001` とやった上で，今回の例外が出ている。
```
Traceback (most recent call last):
  File "C:\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\screen.py", line 284, in run
    self._init_maniplate_db()
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\screen.py", line 265, in _init_maniplate_db
    simulation_db = simulator.sql.SQL(db_path=self.simulation_db_path, schema_path=SCHEMA_PATH)
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\sql.py", line 42, in __init__
    self.read_schema()
  File "C:\Users\ASUS\github.com\umatobi\umatobi\simulator\sql.py", line 47, in read_schema
    self._schema.read_file(f)
  File "C:\Python\Python37\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "C:\Python\Python37\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'cp932' codec can't decode byte 0x88 in position 1081: illegal multibyte sequence
```

**Comment by umedoblock** [comment]
```
umatobi>gvim .git\config
[core]
	editor = gvim '-c "set fenc=utf-8"'
```

**Comment by umedoblock** [comment]
set encoding=utf-8

**Comment by umedoblock** [comment]
`# vim: set fileencoding=utf-8 :`

**Comment by umedoblock** [comment]
https://qiita.com/Fushihara/items/c21172e707d57c833e7e
>git --no-pager log

**Comment by umedoblock** [comment]
対応の目処は立ったってことで。
とりあえず前日くらいまで放置でいいかな。
