### ISSUE TITLE
NameError: name 'simulator' is not defined

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#67]
#62 対応している時に気づいた。
test は通っているんだよね。。。
test が不足しているってこと。
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./simulation.py", line 19, in make_client
    client.start()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 116, in start
    self.client_db = simulator.sql.SQL(db_path=self.client_db_path,
NameError: name 'simulator' is not defined
```

**Comment by umedoblock** [comment]
$ python3 ./simulation.py --simulation-seconds=20 --num-nodes=37
で発生。

**Comment by umedoblock** [comment]
以下も発生。
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./simulation.py", line 18, in make_client
    client.consult_watson()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 75, in consult_watson
    _d_init_attrs = self._init_attrs()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 244, in _init_attrs
    self.schema_path = SCHEMA_PATH
NameError: name 'SCHEMA_PATH' is not defined
```

**Comment by umedoblock** [comment]
どっかでやった。
