### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#7]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/watson.py", line 28, in run
    with WatsonTCPOffice(self.watson) as watson_tcp_office:
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/watson.py", line 40, in __init__
    super().__init__(watson.watson_office_addr, WatsonOffice)
  File "/usr/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by umedoblock** [comment]
done.
