### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#8]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./simulation.py", line 12, in make_client
    client = Client(watson_office_addr, num_nodes)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 62, in __init__
    self._tcp_sock.connect(watson_office_addr)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by umedoblock** [comment]
これ，多分もう再現しない。
