### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by umedoblock** [umedoblock/umatobi#9]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 17, in make_darkness
    darkness_.start()
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/darkness.py", line 152, in start
    self.leave_there.wait()
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 360, in wait
    self._cond.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
  File "./simulation.py", line 13, in make_client
    client.start()
KeyboardInterrupt
  File "/home/umedoblock/git.me/umatobi/umatobi/simulator/client.py", line 130, in start
    recved, recved_addr = self._tcp_sock.recv(1024)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by umedoblock** [comment]
done.
